### ISSUE TITLE
Handle_unknown in OneHotEncoder (FAMD) method

### ISSUE THREAD

**Issue by A-acuto** [MaxHalford/prince#147]
Hi, at the moment, applying the [FAMD method](https://github.com/MaxHalford/prince/blob/master/prince/famd.py) the categorical columns are preprocessed using OneHotEncoder from Sklearn library without any specification on how to handle unknown (so raising errors if new data is encountered).

I was wondering if there the interest of implementing some changes to allow to choose how the unknowns are handled (inherited from [Sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)) either "raising errors", "ignore" or "substitute". 

Thanks for the really handy package!

**Comment by MaxHalford** [comment]
Hey! So you would essentially like to control the `handle_unknown` parameter of the `OneHotEncoder`? The parameters I see there are `{‘error’, ‘ignore’, ‘infrequent_if_exist’}`, but not `substitute`.

**Comment by MaxHalford** [comment]
Ok I've added a `handle_unknown` parameter to FAMD, that will be fed to `OneHotEncoder`. It's available in version 0.10.4 :)

**Comment by TalkativeGuy** [comment]
Hello! I would like to mention that it would be nice to include this parameter for MCE just as you did for FAMD since it uses encodes categorical features aswell. It will have to be rewritten a little since as I see it uses pd.get_dummies instead of OneHotEncoder. I wish I could fork and rewrite it by myself, but I don't have so much time at the moment :(

**Comment by MaxHalford** [comment]
Hey @TalkativeGuy. Actually, for MCA, it's valid to pass columns and column values which were not seen before. Do you have an example/usecase in mind?
