### ISSUE TITLE
Feature idea: biplot

### ISSUE THREAD

**Issue by normanius** [MaxHalford/prince#154]
Have you considered to enhance this package by [biplots](https://en.wikipedia.org/wiki/Biplot), as discussed in [this SO thread](https://stackoverflow.com/questions/39216897)?

Also, I see some potential overlap with the [PCA package](https://erdogant.github.io/pca/pages/html/index.html), though prince appears fitter with regard to the methods. Also, I'm not totally convinced by the API design of the PCA package. Still, maybe there's potential to team up.

I'm dropping these ideas here for further discussion.

**Comment by MaxHalford** [comment]
Hey @normanius 👋

First of all, thanks your activity. It's motivating :)

I definitely agree that biplots are a worthy addition. It's on my roadmap, I just haven't allocated time to it yet. But maybe somebody would like to contribute.

I wasn't aware of the PCA package. It seems to have strong viz capabilities. I will reach out to the package maintainer to see if he wants to consider a merge. I think that's what would be best for community.

**Comment by MaxHalford** [comment]
Just want to mention I've update the `PCA.plot` method so that the column coordinates are scaled to the scale of the row coordinates. This effectively results in the biplot many people are used to. The only difference is that there's no arrows, because those are poorly supported in Altair. But one could argue those clutter the chart.

![Screenshot 2023-06-10 at 19 57 05](https://github.com/MaxHalford/prince/assets/8095957/751a5d0b-e4dc-4afd-81fd-60ea0ccdfe1e)

I've contacted the author of the PCA plot, but there hasn't been much enthusiasm.
