### ISSUE TITLE
MCA with categorical vs ordinal data

### ISSUE THREAD

**Issue by AdrianLsk** [MaxHalford/prince#49]
Hi, thanks for a terrific package.

I have a question regarding the use of categorical vs ordinal data with MCA. What are your suggestions for using prince in such cases?

I found an R package called homals ([github](https://github.com/cran/homals)), where they restrict the matrices differently for each data type (nominal/categorical, ordinal, numerical).

The package implements a generalized version of MCA called homogeneity analysis ([paper](http://gifi.stat.ucla.edu/janspubs/2009/articles/deleeuw_mair_A_09a.pdf)). The calculations regarding restricting the data types (or levels as they call it) start on page 6 (Level constraints: Optimal scaling).

Would it be possible to take it into account in your package as well?

Cheers.

**Comment by MaxHalford** [comment]
Hey,

Thanks for the kind words.

Yeah I guess in the future it would be nice to categorize data as one of (categorical, ordinal, numerical) because at the moment we only do (categorical, numerical). However I really don't have the time to do anything major on `prince` at the moment.

Feel free to make a PR!

Cheers.
